In [2]:
from pathlib import Path

from data_wranglers import TitanicWrangler
from charting_helpers import TitanicChartingHelper

# Titanic Data Exploration

## Load and Prepare Passenger Data

In [3]:
RAW_DATA_PATH = Path("../../data/titanic/titanic_passengers.csv")
assert RAW_DATA_PATH.exists(), f"Raw data file not found at {RAW_DATA_PATH}"

In [4]:
titanic_passengers_raw = TitanicWrangler.load_titanic_data(RAW_DATA_PATH)

In [5]:
titanic_passengers_cleaned = TitanicWrangler.prepare_data(titanic_passengers_raw)

In [6]:
titanic_passengers_cleaned

shape: (1_309, 18)
┌─────────────┬──────────┬────────┬─────────────┬───┬─────────────┬───────┬───────────┬────────────┐
│ PassengerId ┆ Survived ┆ Pclass ┆ Name        ┆ … ┆ TicketShare ┆ Level ┆ FareLog10 ┆ AgeInDecad │
│ ---         ┆ ---      ┆ ---    ┆ ---         ┆   ┆ Count       ┆ ---   ┆ ---       ┆ es         │
│ f64         ┆ str      ┆ i32    ┆ str         ┆   ┆ ---         ┆ str   ┆ f64       ┆ ---        │
│             ┆          ┆        ┆             ┆   ┆ u32         ┆       ┆           ┆ i32        │
╞═════════════╪══════════╪════════╪═════════════╪═══╪═════════════╪═══════╪═══════════╪════════════╡
│ 1.0         ┆ Survived ┆ 1      ┆ Allen,      ┆ … ┆ 4           ┆ B     ┆ 2.324977  ┆ 2          │
│             ┆          ┆        ┆ Miss.       ┆   ┆             ┆       ┆           ┆            │
│             ┆          ┆        ┆ Elisabeth   ┆   ┆             ┆       ┆           ┆            │
│             ┆          ┆        ┆ Walton      ┆   ┆             ┆       ┆           ┆            │
│ 2.0         ┆ Survived ┆ 1      ┆ Allison,    ┆ … ┆ 6           ┆ C     ┆ 2.180556  ┆ 0          │
│             ┆          ┆        ┆ Master.     ┆   ┆             ┆       ┆           ┆            │
│             ┆          ┆        ┆ Hudson      ┆   ┆             ┆       ┆           ┆            │
│             ┆          ┆        ┆ Trevor      ┆   ┆             ┆       ┆           ┆            │
│ 3.0         ┆ Died     ┆ 1      ┆ Allison,    ┆ … ┆ 6           ┆ C     ┆ 2.180556  ┆ 0          │
│             ┆          ┆        ┆ Miss. Helen ┆   ┆             ┆       ┆           ┆            │
│             ┆          ┆        ┆ Loraine     ┆   ┆             ┆       ┆           ┆            │
│ 4.0         ┆ Died     ┆ 1      ┆ Allison,    ┆ … ┆ 6           ┆ C     ┆ 2.180556  ┆ 3          │
│             ┆          ┆        ┆ Mr. Hudson  ┆   ┆             ┆       ┆           ┆            │
│             ┆          ┆        ┆ Joshua Cre… ┆   ┆             ┆       ┆           ┆            │
│ 5.0         ┆ Died     ┆ 1      ┆ Allison,    ┆ … ┆ 6           ┆ C     ┆ 2.180556  ┆ 2          │
│             ┆          ┆        ┆ Mrs. Hudson ┆   ┆             ┆       ┆           ┆            │
│             ┆          ┆        ┆ J C (Bess…  ┆   ┆             ┆       ┆           ┆            │
│ …           ┆ …        ┆ …      ┆ …           ┆ … ┆ …           ┆ …     ┆ …         ┆ …          │
│ 1305.0      ┆ Died     ┆ 3      ┆ Zabour,     ┆ … ┆ 2           ┆ N     ┆ 1.159994  ┆ 1          │
│             ┆          ┆        ┆ Miss.       ┆   ┆             ┆       ┆           ┆            │
│             ┆          ┆        ┆ Hileni      ┆   ┆             ┆       ┆           ┆            │
│ 1306.0      ┆ Died     ┆ 3      ┆ Zabour,     ┆ … ┆ 2           ┆ N     ┆ 1.159994  ┆ 2          │
│             ┆          ┆        ┆ Miss.       ┆   ┆             ┆       ┆           ┆            │
│             ┆          ┆        ┆ Thamine     ┆   ┆             ┆       ┆           ┆            │
│ 1307.0      ┆ Died     ┆ 3      ┆ Zakarian,   ┆ … ┆ 1           ┆ N     ┆ 0.858838  ┆ 2          │
│             ┆          ┆        ┆ Mr.         ┆   ┆             ┆       ┆           ┆            │
│             ┆          ┆        ┆ Mapriededer ┆   ┆             ┆       ┆           ┆            │
│ 1308.0      ┆ Died     ┆ 3      ┆ Zakarian,   ┆ … ┆ 1           ┆ N     ┆ 0.858838  ┆ 2          │
│             ┆          ┆        ┆ Mr. Ortin   ┆   ┆             ┆       ┆           ┆            │
│ 1309.0      ┆ Died     ┆ 3      ┆ Zimmerman,  ┆ … ┆ 1           ┆ N     ┆ 0.896251  ┆ 2          │
│             ┆          ┆        ┆ Mr. Leo     ┆   ┆             ┆       ┆           ┆            │
└─────────────┴──────────┴────────┴─────────────┴───┴─────────────┴───────┴───────────┴────────────┘

In [7]:
titanic_passengers_cleaned.describe()

shape: (9, 19)
┌────────────┬─────────────┬──────────┬──────────┬───┬────────────┬───────┬───────────┬────────────┐
│ statistic  ┆ PassengerId ┆ Survived ┆ Pclass   ┆ … ┆ TicketShar ┆ Level ┆ FareLog10 ┆ AgeInDecad │
│ ---        ┆ ---         ┆ ---      ┆ ---      ┆   ┆ eCount     ┆ ---   ┆ ---       ┆ es         │
│ str        ┆ f64         ┆ str      ┆ f64      ┆   ┆ ---        ┆ str   ┆ f64       ┆ ---        │
│            ┆             ┆          ┆          ┆   ┆ f64        ┆       ┆           ┆ f64        │
╞════════════╪═════════════╪══════════╪══════════╪═══╪════════════╪═══════╪═══════════╪════════════╡
│ count      ┆ 1309.0      ┆ 1309     ┆ 1309.0   ┆ … ┆ 1309.0     ┆ 1309  ┆ 1309.0    ┆ 1309.0     │
│ null_count ┆ 0.0         ┆ 0        ┆ 0.0      ┆ … ┆ 0.0        ┆ 0     ┆ 0.0       ┆ 0.0        │
│ mean       ┆ 655.0       ┆ null     ┆ 2.294882 ┆ … ┆ 2.101604   ┆ null  ┆ 1.263088  ┆ 2.584416   │
│ std        ┆ 378.020061  ┆ null     ┆ 0.837836 ┆ … ┆ 1.779832   ┆ null  ┆ 0.43737   ┆ 1.352289   │
│ min        ┆ 1.0         ┆ Died     ┆ 1.0      ┆ … ┆ 1.0        ┆ A     ┆ 0.0       ┆ 0.0        │
│ 25%        ┆ 328.0       ┆ null     ┆ 2.0      ┆ … ┆ 1.0        ┆ null  ┆ 0.897396  ┆ 2.0        │
│ 50%        ┆ 655.0       ┆ null     ┆ 3.0      ┆ … ┆ 1.0        ┆ null  ┆ 1.159994  ┆ 3.0        │
│ 75%        ┆ 982.0       ┆ null     ┆ 3.0      ┆ … ┆ 3.0        ┆ null  ┆ 1.495197  ┆ 3.0        │
│ max        ┆ 1309.0      ┆ Survived ┆ 3.0      ┆ … ┆ 11.0       ┆ N     ┆ 2.709549  ┆ 8.0        │
└────────────┴─────────────┴──────────┴──────────┴───┴────────────┴───────┴───────────┴────────────┘

In [11]:
titanic_passengers_cleaned.columns

['PassengerId',
 'Survived',
 'Pclass',
 'Name',
 'Sex',
 'Age',
 'SibSp',
 'Parch',
 'Ticket',
 'Fare',
 'Cabin',
 'Embarked',
 'Title',
 'CabinOccupancy',
 'TicketShareCount',
 'Level',
 'FareLog10',
 'AgeInDecades']

## Exploratory Data Analysis

We now explore factors that appear to have contributed towards survival rates on the Titanic 🚢.

Key🔑:
- **N**=number of passengers
- **S**=survival rate

### Women and children first?

This analysis certainly shows a general trend that females were given priority.  It's not so convicing for children!

In [8]:
TitanicChartingHelper.create_strip_boxplot(titanic_passengers_cleaned, 'Sex', 'Age')

### Did wealth have an influence?

Survival rate overall is signfiicantly higher for first class versus third class.

In [9]:
TitanicChartingHelper.create_strip_boxplot(titanic_passengers_cleaned, 'Pclass', 'FareLog10')

### Was occupation a factor?

Interesting that all 8 of the reverands on board perished.

In [10]:
TitanicChartingHelper.create_strip_boxplot(titanic_passengers_cleaned, 'Title', 'Age')