In [94]:
import duckdb
from pathlib import Path
from data_importers import LandRegistryDataImporter, OnsPostcodeDirectoryImporter

## Download data from Land Registry

In [95]:
DATA_PATH = Path("../../data/land_registry/")
assert DATA_PATH.parent.exists(), f"Data path {DATA_PATH} does not exist. Please update the path to point to the correct location of the land registry data."

In [96]:
land_registry_data = LandRegistryDataImporter(DATA_PATH)

In [97]:
# Note - this operation downloads ~150MB per year, so may take a while to run
land_registry_data.download_land_registry_data(2023, 2026)

In [98]:
ONS_PD_DATA_PATH = Path("../../data/ons_postcode_directory/")

In [99]:
ons_postcode_directory_data = OnsPostcodeDirectoryImporter(ONS_PD_DATA_PATH)

In [100]:
# Note - this operation downloads ~1.5GB of data, so may take a while to run
ons_postcode_directory_data.import_data()

## Set up a database and load the raw data into a table

We're going to create a DuckDB database to persist the data we have extracted from the CSV files and then take it through a few transformation steps to finally generate some useful analytics over the data.

In [101]:
from pathlib import Path
LAND_REGISTRY_DATABASE_PATH = Path("../../databases/land_registry.db")

In [102]:
DELETE_EXISTING_DATABASE = False

In [103]:
if LAND_REGISTRY_DATABASE_PATH.exists() and DELETE_EXISTING_DATABASE:
    LAND_REGISTRY_DATABASE_PATH.unlink()
else:
    LAND_REGISTRY_DATABASE_PATH.parent.mkdir(parents=True, exist_ok=True)

In [104]:
db = duckdb.connect(LAND_REGISTRY_DATABASE_PATH)

In [105]:
db.sql("SELECT * from information_schema.tables")

┌───────────────┬──────────────┬─────────────────────────────────────────┬────────────┬──────────────────────────────┬──────────────────────┬───────────────────────────┬──────────────────────────┬────────────────────────┬────────────────────┬──────────┬───────────────┬───────────────┐
│ table_catalog │ table_schema │               table_name                │ table_type │ self_referencing_column_name │ reference_generation │ user_defined_type_catalog │ user_defined_type_schema │ user_defined_type_name │ is_insertable_into │ is_typed │ commit_action │ TABLE_COMMENT │
│    varchar    │   varchar    │                 varchar                 │  varchar   │           varchar            │       varchar        │          varchar          │         varchar          │        varchar         │      varchar       │ varchar  │    varchar    │    varchar    │
├───────────────┼──────────────┼─────────────────────────────────────────┼────────────┼──────────────────────────────┼──────────────────────┼───────────────────────────┼──────────────────────────┼────────────────────────┼────────────────────┼──────────┼───────────────┼───────────────┤
│ land_registry │ bronze       │ postcode_directory                      │ BASE TABLE │ NULL                         │ NULL                 │ NULL                      │ NULL                     │ NULL                   │ YES                │ NO       │ NULL          │ NULL          │
│ land_registry │ bronze       │ price_paid_raw                          │ BASE TABLE │ NULL                         │ NULL                 │ NULL                      │ NULL                     │ NULL                   │ YES                │ NO       │ NULL          │ NULL          │
│ land_registry │ gold         │ locations                               │ VIEW       │ NULL                         │ NULL                 │ NULL                      │ NULL                     │ NULL                   │ NO                 │ NO       │ NULL          │ NULL          │
│ land_registry │ gold         │ median_price_by_month_and_property_type │ VIEW       │ NULL                         │ NULL                 │ NULL                      │ NULL                     │ NULL                   │ NO                 │ NO       │ NULL          │ NULL          │
│ land_registry │ silver       │ price_paid_cleaned                      │ VIEW       │ NULL                         │ NULL                 │ NULL                      │ NULL                     │ NULL                   │ NO                 │ NO       │ NULL          │ NULL          │
└───────────────┴──────────────┴─────────────────────────────────────────┴────────────┴──────────────────────────────┴──────────────────────┴───────────────────────────┴──────────────────────────┴────────────────────────┴────────────────────┴──────────┴───────────────┴───────────────┘

## Load raw data into a table

### Price Paid Data

In [106]:
db.sql("CREATE SCHEMA IF NOT EXISTS bronze")

In [107]:
db.sql(
    f"""
    CREATE TABLE IF NOT EXISTS bronze.price_paid_raw AS
    SELECT
    column00 AS 'id',
    column01 AS 'price',
    column02 AS 'date',
    column03 AS 'postcode',
    column04 AS 'property_type',
    column05 AS 'old_new',
    column06 AS 'duration',
    column07 AS 'paon',
    column08 AS 'saon',
    column09 AS 'street',
    column10 AS 'locale',
    column11 AS 'town_city',
    column12 AS 'district',
    column13 AS 'county',
    column14 AS 'ppd_category',
    column15 AS 'record_type',
    FROM read_csv('{DATA_PATH / "pp-*.csv"}');
    """
)

In [108]:
db.sql("SELECT COUNT (*) FROM bronze.price_paid_raw")

┌──────────────┐
│ count_star() │
│    int64     │
├──────────────┤
│      2739865 │
└──────────────┘

In [109]:
db.sql("FROM bronze.price_paid_raw LIMIT 5")

┌────────────────────────────────────────┬────────┬─────────────────────┬──────────┬───────────────┬─────────┬──────────┬─────────┬─────────┬─────────────────┬───────────┬───────────┬──────────────────┬──────────────────┬──────────────┬─────────────┐
│                   id                   │ price  │        date         │ postcode │ property_type │ old_new │ duration │  paon   │  saon   │     street      │  locale   │ town_city │     district     │      county      │ ppd_category │ record_type │
│                varchar                 │ int64  │      timestamp      │ varchar  │    varchar    │ varchar │ varchar  │ varchar │ varchar │     varchar     │  varchar  │  varchar  │     varchar      │     varchar      │   varchar    │   varchar   │
├────────────────────────────────────────┼────────┼─────────────────────┼──────────┼───────────────┼─────────┼──────────┼─────────┼─────────┼─────────────────┼───────────┼───────────┼──────────────────┼──────────────────┼──────────────┼─────────────┤
│ {0E082196-CE18-5C09-E063-4704A8C0A10E} │ 221000 │ 2023-09-22 00:00:00 │ PL6 6JX  │ T             │ N       │ F        │ 3       │ NULL    │ PILLAR WALK     │ NULL      │ PLYMOUTH  │ CITY OF PLYMOUTH │ CITY OF PLYMOUTH │ A            │ A           │
│ {0E082196-CE19-5C09-E063-4704A8C0A10E} │ 228000 │ 2023-08-25 00:00:00 │ PL7 1SJ  │ S             │ N       │ F        │ 102     │ NULL    │ MERAFIELD ROAD  │ NULL      │ PLYMOUTH  │ CITY OF PLYMOUTH │ CITY OF PLYMOUTH │ A            │ A           │
│ {0E082196-CE1A-5C09-E063-4704A8C0A10E} │ 480000 │ 2023-10-26 00:00:00 │ TQ6 0AS  │ F             │ N       │ L        │ 1A      │ NULL    │ RIVER VIEW      │ KINGSWEAR │ DARTMOUTH │ SOUTH HAMS       │ DEVON            │ A            │ A           │
│ {0E082196-CE1B-5C09-E063-4704A8C0A10E} │ 625000 │ 2023-07-14 00:00:00 │ TQ1 2HB  │ D             │ N       │ F        │ 14      │ NULL    │ OXLEA CLOSE     │ NULL      │ TORQUAY   │ TORBAY           │ TORBAY           │ A            │ A           │
│ {0E082196-CE1C-5C09-E063-4704A8C0A10E} │ 174000 │ 2023-08-04 00:00:00 │ PL2 1LL  │ T             │ N       │ F        │ 58      │ NULL    │ ST AUBYN AVENUE │ NULL      │ PLYMOUTH  │ CITY OF PLYMOUTH │ CITY OF PLYMOUTH │ A            │ A           │
└────────────────────────────────────────┴────────┴─────────────────────┴──────────┴───────────────┴─────────┴──────────┴─────────┴─────────┴─────────────────┴───────────┴───────────┴──────────────────┴──────────────────┴──────────────┴─────────────┘

### ONS Postcode Directory

In [154]:
db.sql(
    f"""
    CREATE TABLE IF NOT EXISTS bronze.postcode_directory AS
    SELECT pcd8 AS 'postcode',
    lat as 'latitude',
    long as 'longitude'
    FROM read_csv('{ONS_PD_DATA_PATH / "*.csv"}', header=true, quote='"');
    """
)

In [156]:
db.sql("SELECT COUNT (*) FROM bronze.postcode_directory")

┌──────────────┐
│ count_star() │
│    int64     │
├──────────────┤
│      2723596 │
└──────────────┘

In [157]:
db.sql("FROM bronze.postcode_directory LIMIT 5")

┌──────────┬───────────┬───────────┐
│ postcode │ latitude  │ longitude │
│ varchar  │  double   │  double   │
├──────────┼───────────┼───────────┤
│ AB1 0AA  │ 57.101459 │ -2.242858 │
│ AB1 0AB  │ 57.102539 │ -2.246315 │
│ AB1 0AD  │ 57.100541 │ -2.248349 │
│ AB1 0AE  │ 57.084429 │ -2.255714 │
│ AB1 0AF  │ 57.096641 │ -2.258109 │
└──────────┴───────────┴───────────┘

In [158]:
db.sql("DESCRIBE bronze.postcode_directory")

┌─────────────┬─────────────┬─────────┬─────────┬─────────┬─────────┐
│ column_name │ column_type │  null   │   key   │ default │  extra  │
│   varchar   │   varchar   │ varchar │ varchar │ varchar │ varchar │
├─────────────┼─────────────┼─────────┼─────────┼─────────┼─────────┤
│ postcode    │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ latitude    │ DOUBLE      │ YES     │ NULL    │ NULL    │ NULL    │
│ longitude   │ DOUBLE      │ YES     │ NULL    │ NULL    │ NULL    │
└─────────────┴─────────────┴─────────┴─────────┴─────────┴─────────┘

## Add features

In [159]:
db.sql("CREATE SCHEMA IF NOT EXISTS silver")

In [160]:
db.sql(
    r"""
    CREATE OR REPLACE VIEW silver.price_paid_cleaned AS
    SELECT
    id,
    price,
    date,
    year(date) AS 'year_of_sale',
    date_trunc('month', date) AS 'month_of_sale',
    CASE property_type
          WHEN 'D' THEN 'Detached'
          WHEN 'S' THEN 'Semi-Detached'
          WHEN 'T' THEN 'Terraced'
          WHEN 'F' THEN 'Flat'
          WHEN 'O' THEN 'Other'
          ELSE property_type
    END AS 'property_type',
    postcode,
    paon,
    saon,
    street,
    locale,
    town_city,
    district,
    county,
    FROM bronze.price_paid_raw
    WHERE property_type <> 'O';
    """
)

In [161]:
db.sql(
    """
    SELECT
    * 
    FROM silver.price_paid_cleaned LIMIT 10
    """
)

┌────────────────────────────────────────┬────────┬─────────────────────┬──────────────┬─────────────────────┬───────────────┬──────────┬─────────┬─────────┬─────────────────┬───────────┬──────────────┬──────────────────┬──────────────────┐
│                   id                   │ price  │        date         │ year_of_sale │    month_of_sale    │ property_type │ postcode │  paon   │  saon   │     street      │  locale   │  town_city   │     district     │      county      │
│                varchar                 │ int64  │      timestamp      │    int64     │      timestamp      │    varchar    │ varchar  │ varchar │ varchar │     varchar     │  varchar  │   varchar    │     varchar      │     varchar      │
├────────────────────────────────────────┼────────┼─────────────────────┼──────────────┼─────────────────────┼───────────────┼──────────┼─────────┼─────────┼─────────────────┼───────────┼──────────────┼──────────────────┼──────────────────┤
│ {0E082196-CE18-5C09-E063-4704A8C0A10E} │ 221000 │ 2023-09-22 00:00:00 │         2023 │ 2023-09-01 00:00:00 │ Terraced      │ PL6 6JX  │ 3       │ NULL    │ PILLAR WALK     │ NULL      │ PLYMOUTH     │ CITY OF PLYMOUTH │ CITY OF PLYMOUTH │
│ {0E082196-CE19-5C09-E063-4704A8C0A10E} │ 228000 │ 2023-08-25 00:00:00 │         2023 │ 2023-08-01 00:00:00 │ Semi-Detached │ PL7 1SJ  │ 102     │ NULL    │ MERAFIELD ROAD  │ NULL      │ PLYMOUTH     │ CITY OF PLYMOUTH │ CITY OF PLYMOUTH │
│ {0E082196-CE1A-5C09-E063-4704A8C0A10E} │ 480000 │ 2023-10-26 00:00:00 │         2023 │ 2023-10-01 00:00:00 │ Flat          │ TQ6 0AS  │ 1A      │ NULL    │ RIVER VIEW      │ KINGSWEAR │ DARTMOUTH    │ SOUTH HAMS       │ DEVON            │
│ {0E082196-CE1B-5C09-E063-4704A8C0A10E} │ 625000 │ 2023-07-14 00:00:00 │         2023 │ 2023-07-01 00:00:00 │ Detached      │ TQ1 2HB  │ 14      │ NULL    │ OXLEA CLOSE     │ NULL      │ TORQUAY      │ TORBAY           │ TORBAY           │
│ {0E082196-CE1C-5C09-E063-4704A8C0A10E} │ 174000 │ 2023-08-04 00:00:00 │         2023 │ 2023-08-01 00:00:00 │ Terraced      │ PL2 1LL  │ 58      │ NULL    │ ST AUBYN AVENUE │ NULL      │ PLYMOUTH     │ CITY OF PLYMOUTH │ CITY OF PLYMOUTH │
│ {0E082196-CE1D-5C09-E063-4704A8C0A10E} │  87500 │ 2023-11-10 00:00:00 │         2023 │ 2023-11-01 00:00:00 │ Flat          │ PL1 4HR  │ 72      │ NULL    │ GEORGE STREET   │ NULL      │ PLYMOUTH     │ CITY OF PLYMOUTH │ CITY OF PLYMOUTH │
│ {0E082196-CE1E-5C09-E063-4704A8C0A10E} │ 260000 │ 2023-12-05 00:00:00 │         2023 │ 2023-12-01 00:00:00 │ Detached      │ PL3 6PT  │ 56      │ NULL    │ REDDINGTON ROAD │ NULL      │ PLYMOUTH     │ CITY OF PLYMOUTH │ CITY OF PLYMOUTH │
│ {0E082196-CE1F-5C09-E063-4704A8C0A10E} │ 200000 │ 2023-11-07 00:00:00 │         2023 │ 2023-11-01 00:00:00 │ Terraced      │ TQ12 6YQ │ 61      │ NULL    │ LUXTON ROAD     │ OGWELL    │ NEWTON ABBOT │ TEIGNBRIDGE      │ DEVON            │
│ {0E082196-CE20-5C09-E063-4704A8C0A10E} │ 150000 │ 2023-11-28 00:00:00 │         2023 │ 2023-11-01 00:00:00 │ Terraced      │ TQ1 1LX  │ 48      │ NULL    │ KENWYN ROAD     │ NULL      │ TORQUAY      │ TORBAY           │ TORBAY           │
│ {0E082196-CE21-5C09-E063-4704A8C0A10E} │ 300000 │ 2023-12-11 00:00:00 │         2023 │ 2023-12-01 00:00:00 │ Terraced      │ TQ7 1AB  │ 89A     │ NULL    │ FORE STREET     │ NULL      │ KINGSBRIDGE  │ SOUTH HAMS       │ DEVON            │
└────────────────────────────────────────┴────────┴─────────────────────┴──────────────┴─────────────────────┴───────────────┴──────────┴─────────┴─────────┴─────────────────┴───────────┴──────────────┴──────────────────┴──────────────────┘
  10 rows                                                                                                                                                                                                                           14 columns

In [170]:
db.sql(
    r"""
    CREATE OR REPLACE VIEW silver.postcodes AS
    SELECT
    postcode AS 'postcode_raw',
    longitude,
    latitude,
    NULLIF(
        regexp_extract(postcode, '^([A-Z]{1,2})[0-9]{1,2}[A-Z]?\s*?[0-9][A-Z]{2}$', 1),
        ''
    ) AS postcode_area,
    NULLIF(
        regexp_extract(postcode, '^([A-Z]{1,2}[0-9]{1,2})[A-Z]?\s*?[0-9][A-Z]{2}$', 1),
        ''
    ) AS postcode_district,
    NULLIF(
        regexp_extract(postcode, '^([A-Z]{1,2}[0-9]{1,2}[A-Z]?\s*?[0-9])[A-Z]{2}$', 1),
        ''
    ) AS postcode_sector,
    NULLIF(
        regexp_extract(postcode, '^([A-Z]{1,2}[0-9]{1,2}[A-Z]?)\s*?[0-9][A-Z]{2}$', 1),
        ''
    ) AS postcode_outward_code,
    NULLIF(
        regexp_extract(postcode, '^[A-Z]{1,2}[0-9]{1,2}[A-Z]?\s*?([0-9][A-Z]{2})$', 1),
        ''
    ) AS postcode_inward_code,
    CONCAT(postcode_outward_code, ' ', postcode_inward_code) AS 'postcode'
    FROM bronze.postcode_directory;
    """
)

In [171]:
db.sql(
    """
    FROM silver.postcodes LIMIT 10
    """
)

┌──────────────┬───────────┬───────────┬───────────────┬───────────────────┬─────────────────┬───────────────────────┬──────────────────────┬──────────┐
│ postcode_raw │ longitude │ latitude  │ postcode_area │ postcode_district │ postcode_sector │ postcode_outward_code │ postcode_inward_code │ postcode │
│   varchar    │  double   │  double   │    varchar    │      varchar      │     varchar     │        varchar        │       varchar        │ varchar  │
├──────────────┼───────────┼───────────┼───────────────┼───────────────────┼─────────────────┼───────────────────────┼──────────────────────┼──────────┤
│ AB1 0AA      │ -2.242858 │ 57.101459 │ AB            │ AB1               │ AB1 0           │ AB1                   │ 0AA                  │ AB1 0AA  │
│ AB1 0AB      │ -2.246315 │ 57.102539 │ AB            │ AB1               │ AB1 0           │ AB1                   │ 0AB                  │ AB1 0AB  │
│ AB1 0AD      │ -2.248349 │ 57.100541 │ AB            │ AB1               │ AB1 0           │ AB1                   │ 0AD                  │ AB1 0AD  │
│ AB1 0AE      │ -2.255714 │ 57.084429 │ AB            │ AB1               │ AB1 0           │ AB1                   │ 0AE                  │ AB1 0AE  │
│ AB1 0AF      │ -2.258109 │ 57.096641 │ AB            │ AB1               │ AB1 0           │ AB1                   │ 0AF                  │ AB1 0AF  │
│ AB1 0AG      │ -2.267519 │  57.09707 │ AB            │ AB1               │ AB1 0           │ AB1                   │ 0AG                  │ AB1 0AG  │
│ AB1 0AJ      │ -2.252861 │ 57.098996 │ AB            │ AB1               │ AB1 0           │ AB1                   │ 0AJ                  │ AB1 0AJ  │
│ AB1 0AL      │ -2.254695 │  57.10175 │ AB            │ AB1               │ AB1 0           │ AB1                   │ 0AL                  │ AB1 0AL  │
│ AB1 0AN      │  -2.24549 │ 57.097537 │ AB            │ AB1               │ AB1 0           │ AB1                   │ 0AN                  │ AB1 0AN  │
│ AB1 0AP      │ -2.245775 │ 57.098229 │ AB            │ AB1               │ AB1 0           │ AB1                   │ 0AP                  │ AB1 0AP  │
└──────────────┴───────────┴───────────┴───────────────┴───────────────────┴─────────────────┴───────────────────────┴──────────────────────┴──────────┘
  10 rows                                                                                                                                    9 columns

In [172]:
db.sql(
    """
    FROM silver.postcodes
    WHERE postcode_area IS NULL
    LIMIT 10
    """
)

┌──────────────┬───────────┬───────────┬───────────────┬───────────────────┬─────────────────┬───────────────────────┬──────────────────────┬──────────┐
│ postcode_raw │ longitude │ latitude  │ postcode_area │ postcode_district │ postcode_sector │ postcode_outward_code │ postcode_inward_code │ postcode │
│   varchar    │  double   │  double   │    varchar    │      varchar      │     varchar     │        varchar        │       varchar        │ varchar  │
├──────────────┼───────────┼───────────┼───────────────┼───────────────────┼─────────────────┼───────────────────────┼──────────────────────┼──────────┤
│ GIR 0AA      │       0.0 │ 99.999999 │ NULL          │ NULL              │ NULL            │ NULL                  │ NULL                 │          │
│ NPT 0AD      │ -2.991593 │ 51.588461 │ NULL          │ NULL              │ NULL            │ NULL                  │ NULL                 │          │
│ NPT 0AE      │ -2.991632 │ 51.590259 │ NULL          │ NULL              │ NULL            │ NULL                  │ NULL                 │          │
│ NPT 0AG      │ -2.991632 │ 51.590259 │ NULL          │ NULL              │ NULL            │ NULL                  │ NULL                 │          │
│ NPT 0AH      │ -2.991632 │ 51.590259 │ NULL          │ NULL              │ NULL            │ NULL                  │ NULL                 │          │
│ NPT 0AJ      │ -2.990189 │ 51.590271 │ NULL          │ NULL              │ NULL            │ NULL                  │ NULL                 │          │
│ NPT 0AL      │ -2.991632 │ 51.590259 │ NULL          │ NULL              │ NULL            │ NULL                  │ NULL                 │          │
│ NPT 0AN      │ -2.990189 │ 51.590271 │ NULL          │ NULL              │ NULL            │ NULL                  │ NULL                 │          │
│ NPT 0AP      │ -2.991593 │ 51.588461 │ NULL          │ NULL              │ NULL            │ NULL                  │ NULL                 │          │
│ NPT 0AQ      │  -2.99013 │ 51.587574 │ NULL          │ NULL              │ NULL            │ NULL                  │ NULL                 │          │
└──────────────┴───────────┴───────────┴───────────────┴───────────────────┴─────────────────┴───────────────────────┴──────────────────────┴──────────┘
  10 rows                                                                                                                                    9 columns

## Checking for orphaned properties

In [173]:
# Join price paid data with postcode data to get longitude and latitude for each property sale
db.sql(
    r"""
    CREATE OR REPLACE VIEW silver.price_paid_geocoded AS
    SELECT
    p.id,
    p.price,
    p.date,
    p.year_of_sale,
    p.month_of_sale,
    p.property_type,
    p.postcode,
    p.paon,
    p.saon,
    p.street,
    p.locale,
    p.town_city,
    p.district,
    p.county,
    s.longitude,
    s.latitude
    FROM silver.price_paid_cleaned p
    LEFT JOIN silver.postcodes s
        ON p.postcode = s.postcode;
    """
)

In [174]:
db.sql(
    """
    FROM silver.price_paid_geocoded
    WHERE longitude IS NULL
    """
)

┌────────────────────────────────────────┬─────────┬─────────────────────┬──────────────┬─────────────────────┬───────────────┬──────────┬──────────────────────────────┬───────────┬──────────────────────┬───────────────────────┬─────────────────────┬──────────────────────────┬──────────────────────────┬───────────┬──────────┐
│                   id                   │  price  │        date         │ year_of_sale │    month_of_sale    │ property_type │ postcode │             paon             │   saon    │        street        │        locale         │      town_city      │         district         │          county          │ longitude │ latitude │
│                varchar                 │  int64  │      timestamp      │    int64     │      timestamp      │    varchar    │ varchar  │           varchar            │  varchar  │       varchar        │        varchar        │       varchar       │         varchar          │         varchar          │  double   │  double  │
├────────────────────────────────────────┼─────────┼─────────────────────┼──────────────┼─────────────────────┼───────────────┼──────────┼──────────────────────────────┼───────────┼──────────────────────┼───────────────────────┼─────────────────────┼──────────────────────────┼──────────────────────────┼───────────┼──────────┤
│ {045A1898-6C6B-9A24-E063-4804A8C048EA} │  215000 │ 2023-07-21 00:00:00 │         2023 │ 2023-07-01 00:00:00 │ Detached      │ NULL     │ 22                           │ NULL      │ MINFFORDD            │ LLANRUG               │ CAERNARFON          │ GWYNEDD                  │ GWYNEDD                  │      NULL │     NULL │
│ {045A1898-6A94-9A24-E063-4804A8C048EA} │  178000 │ 2023-08-11 00:00:00 │         2023 │ 2023-08-01 00:00:00 │ Flat          │ NULL     │ ACADIA HOUSE                 │ 3A        │ WARREN STREET        │ NULL                  │ TENBY               │ PEMBROKESHIRE            │ PEMBROKESHIRE            │      NULL │     NULL │
│ {FFA361DB-66A9-8A03-E053-4804A8C01F61} │  319500 │ 2023-01-26 00:00:00 │         2023 │ 2023-01-01 00:00:00 │ Detached      │ NULL     │ WAWNE HILL FARM              │ NULL      │ NULL                 │ MEAUX                 │ BEVERLEY            │ EAST RIDING OF YORKSHIRE │ EAST RIDING OF YORKSHIRE │      NULL │     NULL │
│ {FFA361DB-62C6-8A03-E053-4804A8C01F61} │  120000 │ 2023-04-19 00:00:00 │         2023 │ 2023-04-01 00:00:00 │ Terraced      │ NULL     │ 102                          │ NULL      │ UNITY TERRACE        │ RIPPONDEN             │ SOWERBY BRIDGE      │ CALDERDALE               │ WEST YORKSHIRE           │      NULL │     NULL │
│ {0B853950-ED61-69A5-E063-4704A8C07DAC} │  264000 │ 2023-09-01 00:00:00 │         2023 │ 2023-09-01 00:00:00 │ Terraced      │ NULL     │ BEAUFORT PARK                │ GARAGE 38 │ STATION ROAD         │ ROYAL WOOTTON BASSETT │ SWINDON             │ WILTSHIRE                │ WILTSHIRE                │      NULL │     NULL │
│ {0B853950-EB7C-69A5-E063-4704A8C07DAC} │  200000 │ 2023-11-06 00:00:00 │         2023 │ 2023-11-01 00:00:00 │ Detached      │ NULL     │ CAROL LODGE                  │ GARAGE    │ TRUGGIST LANE        │ BERKSWELL             │ COVENTRY            │ SOLIHULL                 │ WEST MIDLANDS            │      NULL │     NULL │
│ {1775CCF8-056B-38BA-E063-4704A8C05A7C} │  199000 │ 2023-12-04 00:00:00 │         2023 │ 2023-12-01 00:00:00 │ Terraced      │ NULL     │ 229                          │ NULL      │ WESTGATE ROAD        │ NULL                  │ NEWCASTLE UPON TYNE │ NEWCASTLE UPON TYNE      │ TYNE AND WEAR            │      NULL │     NULL │
│ {0B853950-EEFD-69A5-E063-4704A8C07DAC} │  145000 │ 2023-09-29 00:00:00 │         2023 │ 2023-09-01 00:00:00 │ Flat          │ NULL     │ ST PAUL'S COURT              │ 4         │ ST PAULS STREET      │ NULL                  │ LEEDS               │ LEEDS                    │ WEST YORKSHIRE           │      NULL │     NULL │
│ {1C3E72FD-F56B-F410-E063-4804A8C0DFA6} │  112000 │ 2023-04-05 00:00:00 │         2023 │ 2023-04-01 00:00:00 │ Detached      │ NULL     │ REHOBOTH CHAPEL              │ NULL      │ NULL                 │ MATHRY                │ HAVERFORDWEST       │ PEMBROKESHIRE            │ PEMBROKESHIRE            │      NULL │     NULL │
│ {09266DDC-54FD-AF90-E063-4704A8C02087} │ 1000001 │ 2023-06-29 00:00:00 │         2023 │ 2023-06-01 00:00:00 │ Detached      │ NULL     │ PLOTS 162 163 287 305 TO 308 │ NULL      │ ROYAL VICTORIA COURT │ NULL                  │ NEWPORT             │ NEWPORT                  │ NEWPORT                  │      NULL │     NULL │
│                   ·                    │    ·    │          ·          │           ·  │          ·          │  ·            │  ·       │ ·                            │  ·        │        ·             │  ·                    │   ·                 │    ·                     │    ·                     │        ·  │       ·  │
│                   ·                    │    ·    │          ·          │           ·  │          ·          │  ·            │  ·       │ ·                            │  ·        │        ·             │  ·                    │   ·                 │    ·                     │    ·                     │        ·  │       ·  │
│                   ·                    │    ·    │          ·          │           ·  │          ·          │  ·            │  ·       │ ·                            │  ·        │        ·             │  ·                    │   ·                 │    ·                     │    ·                     │        ·  │       ·  │
│ {402A3A66-CF92-A7DF-E063-4804A8C0B80D} │ 1075000 │ 2025-08-28 00:00:00 │         2025 │ 2025-08-01 00:00:00 │ Flat          │ W1K 2FD  │ 5                            │ FLAT 2    │ DUNRAVEN STREET      │ NULL                  │ LONDON              │ CITY OF WESTMINSTER      │ GREATER LONDON           │      NULL │     NULL │
│ {1A0C5C63-F896-7CBE-E063-4804A8C06C96} │  255000 │ 2024-04-26 00:00:00 │         2024 │ 2024-04-01 00:00:00 │ Terraced      │ CT11 8FZ │ 1                            │ NULL      │ KENT STEPS           │ NULL                  │ RAMSGATE            │ THANET                   │ KENT                     │      NULL │     NULL │
│ {2131FCF6-C419-86E8-E063-4804A8C0372B} │  202000 │ 2023-05-30 00:00:00 │         2023 │ 2023-05-01 00:00:00 │ Semi-Detached │ TS21 1GQ │ 3                            │ NULL      │ HARMBY WAY           │ NULL                  │ STOCKTON-ON-TEES    │ STOCKTON-ON-TEES         │ STOCKTON-ON-TEES         │      NULL │     NULL │
│ {2131FCF6-C41A-86E8-E063-4804A8C0372B} │  190000 │ 2023-05-30 00:00:00 │         2023 │ 2023-05-01 00:00:00 │ Semi-Detached │ TS21 1GQ │ 2                            │ NULL      │ HARMBY WAY           │ NULL                  │ STOCKTON-ON-TEES    │ STOCKTON-ON-TEES         │ STOCKTON-ON-TEES         │      NULL │     NULL │
│ {2131FCF6-C41B-86E8-E063-4804A8C0372B} │  266000 │ 2023-05-30 00:00:00 │         2023 │ 2023-05-01 00:00:00 │ Detached      │ TS21 1GQ │ 1                            │ NULL      │ HARMBY WAY           │ NULL                  │ STOCKTON-ON-TEES    │ STOCKTON-ON-TEES         │ STOCKTON-ON-TEES         │      NULL │     NULL │
│ {2F7F2B43-D1D3-E08F-E063-4804A8C05A49} │  275231 │ 2024-06-28 00:00:00 │         2024 │ 2024-06-01 00:00:00 │ Detached      │ DN33 3FF │ 41                           │ NULL      │ ROSS WAY             │ SCARTHO TOP           │ GRIMSBY             │ NORTH EAST LINCOLNSHIRE  │ NORTH EAST LINCOLNSHIRE  │      NULL │     NULL │
│ {4777E0AF-2130-5D59-E063-4804A8C09F8E} │  220000 │ 2025-12-01 00:00:00 │         2025 │ 2025-12-01 00:00:00 │ Terraced      │ NR33 3FB │ 4                            │ NULL      │ MANOR RISE           │ CARLTON COLVILLE      │ LOWESTOFT           │ EAST SUFFOLK             │ SUFFOLK                  │      NULL │     NULL │
│ {4E75C29D-F9FD-8922-E063-4804A8C094D0} │  416141 │ 2025-12-19 00:00:00 │         2025 │ 2025-12-01 00:00:00 │ Detached      │ CM6 4HE  │ 2                            │ NULL      │ SKATER GARDENS       │ NULL                  │ DUNMOW              │ UTTLESFORD               │ ESSEX                    │      NULL │     NULL │
│ {09266DDC-342B-AF90-E063-4704A8C02087} │  380000 │ 2023-09-08 00:00:00 │         2023 │ 2023-09-01 00:00:00 │ Flat          │ CV23 5QX │ 26                           │ FLAT 5    │ CLARENDON SQUARE     │ NULL                  │ LEAMINGTON SPA      │ WARWICK                  │ WARWICKSHIRE             │      NULL │     NULL │
│ {06C9F487-3B40-9388-E063-4804A8C0BD98} │  237500 │ 2023-08-25 00:00:00 │         2023 │ 2023-08-01 00:00:00 │ Detached      │ LL60 6BD │ GADLYS                       │ NULL      │ HOLYHEAD ROAD        │ NULL                  │ GAERWEN             │ ISLE OF ANGLESEY         │ ISLE OF ANGLESEY         │      NULL │     NULL │
└────────────────────────────────────────┴─────────┴─────────────────────┴──────────────┴─────────────────────┴───────────────┴──────────┴──────────────────────────────┴───────────┴──────────────────────┴───────────────────────┴─────────────────────┴──────────────────────────┴──────────────────────────┴───────────┴──────────┘
  798 rows (20 shown)                                                                                                                                                                                                                                                                                                      16 columns

## Projecting insights

### Monthly statistics by property type

In [79]:
db.sql("CREATE SCHEMA IF NOT EXISTS gold")

In [80]:
db.sql(
    """
    CREATE OR REPLACE VIEW gold.median_price_by_month_and_property_type AS
    SELECT
    property_type,
    month_of_sale,
    MEDIAN(price) AS median_price
    FROM silver.price_paid_cleaned
    GROUP BY ALL
    ORDER BY month_of_sale, property_type;
    """
)

In [81]:
db.sql("FROM gold.median_price_by_month_and_property_type")

┌───────────────┬─────────────────────┬──────────────┐
│ property_type │    month_of_sale    │ median_price │
│    varchar    │      timestamp      │    double    │
├───────────────┼─────────────────────┼──────────────┤
│ Detached      │ 2023-01-01 00:00:00 │     430000.0 │
│ Flat          │ 2023-01-01 00:00:00 │     238000.0 │
│ Semi-Detached │ 2023-01-01 00:00:00 │     260000.0 │
│ Terraced      │ 2023-01-01 00:00:00 │     212795.0 │
│ Detached      │ 2023-02-01 00:00:00 │     420000.0 │
│ Flat          │ 2023-02-01 00:00:00 │     230000.0 │
│ Semi-Detached │ 2023-02-01 00:00:00 │     256000.0 │
│ Terraced      │ 2023-02-01 00:00:00 │     212500.0 │
│ Detached      │ 2023-03-01 00:00:00 │     414995.0 │
│ Flat          │ 2023-03-01 00:00:00 │     227744.0 │
│  ·            │          ·          │         ·    │
│  ·            │          ·          │         ·    │
│  ·            │          ·          │         ·    │
│ Semi-Detached │ 2026-01-01 00:00:00 │     270000.0 │
│ Terraced      │ 2026-01-01 00:00:00 │     225000.0 │
│ Detached      │ 2026-02-01 00:00:00 │     410000.0 │
│ Flat          │ 2026-02-01 00:00:00 │     205000.0 │
│ Semi-Detached │ 2026-02-01 00:00:00 │     270000.0 │
│ Terraced      │ 2026-02-01 00:00:00 │     222250.0 │
│ Detached      │ 2026-03-01 00:00:00 │     405000.0 │
│ Flat          │ 2026-03-01 00:00:00 │     210000.0 │
│ Semi-Detached │ 2026-03-01 00:00:00 │     267500.0 │
│ Terraced      │ 2026-03-01 00:00:00 │     222000.0 │
└───────────────┴─────────────────────┴──────────────┘
  156 rows (20 shown)                      3 columns

### Location dimension

In [82]:
db.sql(
    """
    CREATE OR REPLACE VIEW gold.locations AS
    SELECT
    town_city,
    district,
    county
    FROM silver.price_paid_cleaned
    WHERE property_type <> 'Other'
    GROUP BY ALL
    ORDER BY county, district, town_city;
    """
)

In [83]:
db.sql("SELECT COUNT(*) FROM gold.locations")

┌──────────────┐
│ count_star() │
│    int64     │
├──────────────┤
│         2540 │
└──────────────┘

## Inspect contents of database

In [84]:
db.sql("SELECT * from information_schema.tables")

┌───────────────┬──────────────┬─────────────────────────────────────────┬────────────┬──────────────────────────────┬──────────────────────┬───────────────────────────┬──────────────────────────┬────────────────────────┬────────────────────┬──────────┬───────────────┬───────────────┐
│ table_catalog │ table_schema │               table_name                │ table_type │ self_referencing_column_name │ reference_generation │ user_defined_type_catalog │ user_defined_type_schema │ user_defined_type_name │ is_insertable_into │ is_typed │ commit_action │ TABLE_COMMENT │
│    varchar    │   varchar    │                 varchar                 │  varchar   │           varchar            │       varchar        │          varchar          │         varchar          │        varchar         │      varchar       │ varchar  │    varchar    │    varchar    │
├───────────────┼──────────────┼─────────────────────────────────────────┼────────────┼──────────────────────────────┼──────────────────────┼───────────────────────────┼──────────────────────────┼────────────────────────┼────────────────────┼──────────┼───────────────┼───────────────┤
│ land_registry │ bronze       │ postcode_directory                      │ BASE TABLE │ NULL                         │ NULL                 │ NULL                      │ NULL                     │ NULL                   │ YES                │ NO       │ NULL          │ NULL          │
│ land_registry │ bronze       │ price_paid_raw                          │ BASE TABLE │ NULL                         │ NULL                 │ NULL                      │ NULL                     │ NULL                   │ YES                │ NO       │ NULL          │ NULL          │
│ land_registry │ gold         │ locations                               │ VIEW       │ NULL                         │ NULL                 │ NULL                      │ NULL                     │ NULL                   │ NO                 │ NO       │ NULL          │ NULL          │
│ land_registry │ gold         │ median_price_by_month_and_property_type │ VIEW       │ NULL                         │ NULL                 │ NULL                      │ NULL                     │ NULL                   │ NO                 │ NO       │ NULL          │ NULL          │
│ land_registry │ silver       │ price_paid_cleaned                      │ VIEW       │ NULL                         │ NULL                 │ NULL                      │ NULL                     │ NULL                   │ NO                 │ NO       │ NULL          │ NULL          │
└───────────────┴──────────────┴─────────────────────────────────────────┴────────────┴──────────────────────────────┴──────────────────────┴───────────────────────────┴──────────────────────────┴────────────────────────┴────────────────────┴──────────┴───────────────┴───────────────┘

## Inspect the files

In [85]:
database_files = list(LAND_REGISTRY_DATABASE_PATH.parent.glob("*.db"))
csv_files = list(DATA_PATH.glob("*.csv"))

In [86]:
database_files

[PosixPath('../../databases/land_registry.db')]

In [87]:
import polars as pl

files_to_analyse = pl.DataFrame(
    { 
        "file_name": [f.name for f in database_files + csv_files],
        "file_size": [f.stat().st_size for f in database_files + csv_files],
        "file_type": [f.suffix for f in database_files + csv_files]
    }
)

In [88]:
files_to_analyse

shape: (5, 3)
┌──────────────────┬───────────┬───────────┐
│ file_name        ┆ file_size ┆ file_type │
│ ---              ┆ ---       ┆ ---       │
│ str              ┆ i64       ┆ str       │
╞══════════════════╪═══════════╪═══════════╡
│ land_registry.db ┆ 153104384 ┆ .db       │
│ pp-2025.csv      ┆ 147899769 ┆ .csv      │
│ pp-2023.csv      ┆ 150073808 ┆ .csv      │
│ pp-2024.csv      ┆ 161466225 ┆ .csv      │
│ pp-2026.csv      ┆ 18087606  ┆ .csv      │
└──────────────────┴───────────┴───────────┘

In [89]:
(
    files_to_analyse
    .group_by("file_type")
    .agg(pl.col("file_size").sum().alias("total_file_size"))
    .with_columns((pl.col("total_file_size") / (1024 * 1024 * 1024)).alias("total_file_size_gb"))
)

shape: (2, 3)
┌───────────┬─────────────────┬────────────────────┐
│ file_type ┆ total_file_size ┆ total_file_size_gb │
│ ---       ┆ ---             ┆ ---                │
│ str       ┆ i64             ┆ f64                │
╞═══════════╪═════════════════╪════════════════════╡
│ .db       ┆ 153104384       ┆ 0.14259            │
│ .csv      ┆ 477527408       ┆ 0.444732           │
└───────────┴─────────────────┴────────────────────┘

In [90]:
# Calculate total sizes for .db and .csv files
db_size = files_to_analyse.filter(pl.col("file_type") == ".db")["file_size"].sum()
csv_size = files_to_analyse.filter(pl.col("file_type") == ".csv")["file_size"].sum()

# Calculate compression percentage
compression_percentage = (db_size / csv_size) * 100
print(f"DuckDB database is {compression_percentage:.1f}% of the original size of the CSV files.")

DuckDB database is 32.1% of the original size of the CSV files.

## Add visualisation over the analytics

Finally we convert the Gold `average_price_by_month_and_property_type` view to a Polars dataframe so we can visualise the data on a line chart using the Plotly Express charting package.

In [91]:
import plotly.express as px

fig = px.line(
    db.sql("FROM gold.median_price_by_month_and_property_type").pl(),
    x="month_of_sale",
    y="median_price",
    color="property_type",
    line_dash="property_type",
    color_discrete_sequence=["#8CC600", "black", "darkgrey", "#EE7423"],
    line_dash_sequence=["solid", "dash", "dot", "dashdot"],
    title="Median Price by Month and Property Type"
)

fig.update_layout(
    xaxis_title="Month",
    yaxis_title="Median Price",
    legend_title="Property Type",
)

fig.show()

In [92]:
db.close()